export type CheckoutTable = {
    order_id: number
    name: string
    status: string
    type: string
    product: string
    price: number
    quantity: number
    amount: number
} 

export const checkoutData: CheckoutTable[] = [
  {
    order_id: 48291,
    name: "Budi Santoso",
    status: "pending",
    type: "delivery",
    product: "Kopi Arabica",
    price: 55000,
    quantity: 2,
    amount: 110000,
  },
  {
    order_id: 19384,
    name: "Siti Aminah",
    status: "success",
    type: "pickup",
    product: "Teh Hijau",
    price: 35000,
    quantity: 1,
    amount: 35000,
  },
  {
    order_id: 72914,
    name: "Dewi Lestari",
    status: "cancel",
    type: "delivery",
    product: "Coklat Premium",
    price: 45000,
    quantity: 3,
    amount: 135000,
  },
  {
    order_id: 56402,
    name: "Rudi Hartono",
    status: "delivery",
    type: "delivery",
    product: "Keripik Pisang",
    price: 20000,
    quantity: 5,
    amount: 100000,
  },
  {
    order_id: 83751,
    name: "Ayu Wulandari",
    status: "pending",
    type: "pickup",
    product: "Madu Hutan",
    price: 75000,
    quantity: 1,
    amount: 75000,
  },
  {
    order_id: 10458,
    name: "Dimas Saputra",
    status: "success",
    type: "delivery",
    product: "Susu Almond",
    price: 40000,
    quantity: 2,
    amount: 80000,
  },
  {
    order_id: 91573,
    name: "Wahyu Pratama",
    status: "cancel",
    type: "pickup",
    product: "Roti Gandum",
    price: 25000,
    quantity: 4,
    amount: 100000,
  },
  {
    order_id: 68329,
    name: "Nina Andriani",
    status: "delivery",
    type: "delivery",
    product: "Minyak Zaitun",
    price: 90000,
    quantity: 1,
    amount: 90000,
  },
  {
    order_id: 24781,
    name: "Agus Salim",
    status: "success",
    type: "pickup",
    product: "Beras Organik",
    price: 65000,
    quantity: 2,
    amount: 130000,
  },
  {
    order_id: 59013,
    name: "Putri Maharani",
    status: "pending",
    type: "delivery",
    product: "Granola Mix",
    price: 50000,
    quantity: 3,
    amount: 150000,
  },
  {
    order_id: 31875,
    name: "Rangga Aditya",
    status: "delivery",
    type: "pickup",
    product: "Kacang Mete",
    price: 80000,
    quantity: 1,
    amount: 80000,
  },
  {
    order_id: 72981,
    name: "Lina Marlina",
    status: "success",
    type: "delivery",
    product: "Jus Buah Botol",
    price: 15000,
    quantity: 6,
    amount: 90000,
  },
  {
    order_id: 86014,
    name: "Farhan Maulana",
    status: "cancel",
    type: "pickup",
    product: "Mi Organik",
    price: 18000,
    quantity: 4,
    amount: 72000,
  },
  {
    order_id: 44190,
    name: "Gita Saputri",
    status: "delivery",
    type: "delivery",
    product: "Biskuit Oat",
    price: 30000,
    quantity: 2,
    amount: 60000,
  },
  {
    order_id: 50763,
    name: "Yoga Satria",
    status: "pending",
    type: "pickup",
    product: "Air Mineral 1L",
    price: 7000,
    quantity: 10,
    amount: 70000,
  },
  {
    order_id: 69204,
    name: "Salsa Amanda",
    status: "success",
    type: "delivery",
    product: "Keju Cheddar",
    price: 32000,
    quantity: 3,
    amount: 96000,
  },
  {
    order_id: 12897,
    name: "Aldi Firmansyah",
    status: "cancel",
    type: "pickup",
    product: "Tepung Terigu",
    price: 14000,
    quantity: 5,
    amount: 70000,
  },
  {
    order_id: 87320,
    name: "Melati Anggraini",
    status: "delivery",
    type: "delivery",
    product: "Garam Himalaya",
    price: 25000,
    quantity: 1,
    amount: 25000,
  },
  {
    order_id: 36058,
    name: "Kevin Pratama",
    status: "pending",
    type: "pickup",
    product: "Selai Kacang",
    price: 28000,
    quantity: 2,
    amount: 56000,
  },
  {
    order_id: 98142,
    name: "Ratna Dewi",
    status: "success",
    type: "delivery",
    product: "Yogurt Cup",
    price: 12000,
    quantity: 4,
    amount: 48000,
  }
];
